PCHR-1576: Menu updates
compucorp/civihr-employee-portal-theme pull request #100
Opened 2016-09-20 05:23 UTC by deb1990

# Requirement

1. On mobile version remove a separate dropdown for logo. 
![image](https://cloud.githubusercontent.com/assets/5058867/18658373/dfa9f1bc-7f1f-11e6-9488-6ed6004335ce.png)

2. On click on logo let's open the menu under the burger icon with those two links moved to the first dropdown

# Fix
1. Removed the dropdown shown on above screenshot.
2. Added 2 new menu items which is shown only on mobile version(using CSS).
![anim](https://cloud.githubusercontent.com/assets/5058867/18658424/719daa96-7f20-11e6-9034-b15ae3499c98.gif)
3. Open menu on clicking the logo

2016-09-20 09:00 UTC, JonScreat commented
Looks good to me

2016-09-20 09:02 UTC, mi-kon commented
LGTM

2016-09-20 09:04 UTC, AkA84 commented
Is it normal that those two links appear just like the other ones? Seems to me they should be visually separated or highlighted from the rest

2016-09-20 09:08 UTC, mi-kon commented
Yeah, I think it's fine for now.

2016-09-20 09:09 UTC, AkA84 approved these changes

2016-09-20 09:15 UTC, JonScreat commented
Reposted from https://github.com/compucorp/civihr-employee-portal/pull/201

> I think it would be worth differentiating the Admin and SSP links from the others as they serve a different purpose and so should sit differently in the hierarchy. Is this something that's possible to do?

2016-09-20 09:52 UTC, deb1990 commented
@JonScreat What exactly should we do.  A different border/background or something else?

2016-09-20 15:36 UTC, JonScreat commented
I suggest something like this, using the grey background to show the importance of these two options.

![ssp menu m - alt 2x](https://cloud.githubusercontent.com/assets/19689834/18677340/638af712-7f50-11e6-8543-2f24159cc648.png)

2016-09-22 06:24 UTC, deb1990 commented
Menu padding fixed 
![image](https://cloud.githubusercontent.com/assets/5058867/18738654/3a18fac0-80bb-11e6-943e-cf09666f1523.png)

2016-09-22 06:53 UTC, JonScreat commented
Looks good to me

2016-09-22 08:44 UTC, AkA84 approved these changes

2016-09-23 08:30 UTC, deb1990 commented
SSP bottom border removed
![image](https://cloud.githubusercontent.com/assets/5058867/18779296/09b9ca0e-8196-11e6-999d-bfa9a8d21fd2.png)

2016-09-23 08:32 UTC, AkA84 commented on civihr_default_theme/scss/partials/_menu.scss
> +  .menu-link-civihr-ssp>a {
```scss
.menu-link-civihr-ssp > a {

}
```
please leave a space around the `>`

(applies for all other instances)

2016-09-23 08:32 UTC, AkA84 requested changes

2016-09-23 08:33 UTC, JonScreat commented
Looks good to me

2016-09-23 08:38 UTC, AkA84 approved these changes

2016-09-23 08:50 UTC, merged