PCHR-1725: Menu show/hide condition changed
compucorp/civihr-employee-portal-theme pull request #115
Opened 2016-11-18 05:45 UTC by deb1990

**Requirement**
For civihr_staff or civihr_manager (any role without 'For civihr_staff or civihr_manager (any role without 'access civicrm' permision):
1. Don't show dropdown on hover
2. Make Home link clickable itself and link to /dashboard' permission):
1. Don't show dropdown on hover
2. Make Home link clickable itself and link to /dashboard
![image-2016-11-16-11-30-56-075](https://cloud.githubusercontent.com/assets/5058867/20419948/e2d2e8ce-ad7f-11e6-8e3f-d733eef3b23e.png)

**Fix**
1. Hiding the menu if user does not have `access CiviCRM`
2. Made the whole Home link clickable  if user does not have `access CiviCRM`

2016-11-18 08:19 UTC, AkA84 requested changes

2016-11-18 08:19 UTC, AkA84 commented on civihr_default_theme/templates/page/page.tpl.php
> +      <?php if (!user_access("access CiviCRM")) { ?>
Couldn't you store this check result in a variable, before all the markup? You are doing the same check twice
```php
$civi_access = user_access("access CiviCRM");
```

2016-11-18 08:19 UTC, AkA84 commented on civihr_default_theme/scss/partials/_menu.scss
> +  color: $light;
Are you also adjusting the menu color? Was it part of the ticket requirements? It wasn't mentioned in the PR

2016-11-18 08:19 UTC, AkA84 commented on civihr_default_theme/templates/page/page.tpl.php
> +            <span class="chr_brand__icon icon-logo"></span>
4 spaces indentation

2016-11-18 08:19 UTC, AkA84 commented on civihr_default_theme/templates/page/page.tpl.php
> +      <?php }?>
I think it's better to use `endif` in these cases, makes the code more readable (http://php.net/manual/en/control-structures.alternative-syntax.php)

2016-11-21 08:10 UTC, deb1990 commented on civihr_default_theme/scss/partials/_menu.scss
> +  color: $light;
Previously the menu was always a `span`, now sometimes its `anchor` when `civicrm` access is not there. So had to explicitly mention the color. Result is same as before.

2016-11-21 10:29 UTC, AkA84 approved these changes

2016-12-07 15:12 UTC, AkA84 requested changes
I'm a bit worried by the fact that the solution consists in copy, pasting and changing the original `menu_link__dropdown` hook contained in radix.

That doesn't look right, and if instead it is, then please provide the documentation/tutorial/something that shows that it is indeed the only proper way to do it

2016-12-07 15:12 UTC, AkA84 commented on civihr_default_theme/scss/partials/_layout.scss
> +    .chr_header__corner {
You are using 4 spaces indent, instead of 2 spaces (applies to all changes)

2016-12-07 15:12 UTC, AkA84 commented on civihr_default_theme/template.php
> +{
The opening parenthesis should be on the same line with `function`

2016-12-07 15:12 UTC, AkA84 commented on civihr_default_theme/template.php
> + *
You are doing a lot of stuff in this method, please explain what in the documentation

2016-12-07 15:12 UTC, AkA84 commented on civihr_default_theme/template.php
> +    //Hide the links to civicrm and dashboard if Access to CiviCRM is not present
If we really need to copy paste the entire `menu_link__dropdown` function (and again, I want to make sure that this is the *very* last resort), then at least put your "code added" stuff in a separate function

2016-12-08 14:55 UTC, AkA84 approved these changes

2016-12-08 15:02 UTC, merged