PCHR-1273: Calendar Styles
compucorp/civihr-employee-portal-theme pull request #137
Opened 2017-02-05 15:07 UTC by deb1990

2017-02-06 09:44 UTC, dhavalsharma requested changes

2017-02-06 09:44 UTC, dhavalsharma commented on civihr_default_theme/scss/components/_ui-select.scss
> +    -webkit-font-smoothing: antialiased;
font smoothing has limited support [across browsers](https://developer.mozilla.org/en-US/docs/Web/CSS/font-smooth)? Also only webkit is used here?

2017-02-06 12:36 UTC, deb1990 commented on civihr_default_theme/scss/components/_ui-select.scss
> +    -webkit-font-smoothing: antialiased;
I used `font-smoothing` code from `_custom-select.scss` which was already present, now moved the code to a mixin and added `moz` prefix.
Reference: https://davidwalsh.name/font-smoothing

2017-02-06 12:37 UTC, AkA84 requested changes

2017-02-06 12:37 UTC, AkA84 commented on civihr_default_theme/scss/components/_leave-calendar.scss
> +  background-color: #41afcb !important;
Why some have `important!` and some do not?

2017-02-06 12:49 UTC, deb1990 commented on civihr_default_theme/scss/components/_leave-calendar.scss
> +  background-color: #41afcb !important;
Kept `!important` for `weekend` and `non-working`day to give them more priority. 
Example: If a date is weekend and also a leaveRequest is there for that date, showing colors for the `weekend` as leave is not calculated for that day.

2017-02-07 09:00 UTC, AkA84 approved these changes

2017-02-07 09:15 UTC, dhavalsharma approved these changes

2017-02-07 10:41 UTC, merged