PCHR-1862: Pad date text to left in date picker
compucorp/civihr-employee-portal-theme pull request #151
Opened 2017-03-29 09:22 UTC by dhavalsharma

Add padding to date text in date picker to shift it to left. Now the date text is not getting clipped.

![image](https://cloud.githubusercontent.com/assets/89973/24447586/20781aac-148f-11e7-93a8-057191f507be.png)

2017-03-29 10:33 UTC, AkA84 requested changes
can we fix this by using bootstrap grid (`col-sm-6`, etc), instead of ad-hoc magic numbers?

2017-03-29 11:20 UTC, dhavalsharma commented
grid ones are not working , either its becoming too long and displacing the other dropdown or too small to clip date

2017-03-29 14:19 UTC, AkA84 commented
@dhavalsharma can you show a screenshot of that? not sure how it can displaced the other dropdowns if you adjust all the grid cells accordingly

2017-03-30 04:22 UTC, dhavalsharma commented
with xs-5 it leaves lots of white space
![image](https://cloud.githubusercontent.com/assets/89973/24487604/70feb14e-152e-11e7-9978-5f8dfbedd4d4.png)

2017-03-31 06:43 UTC, AkA84 requested changes

2017-03-31 06:43 UTC, AkA84 commented on civihr_default_theme/scss/components/_leave-request-modal.scss
> +.chr_leave-request-modal__input-font-size {
this is just a hack, we don't need an entire new selector, can't you just reference classes/tags that are already there? this is a bit overkill

2017-03-31 06:43 UTC, AkA84 commented on civihr_default_theme/scss/components/_leave-request-modal.scss
> +.chr_leave-request-modal__span-expiry {
This looks an ad-hoc fix, did you see what the reason is for the misalingment in the first place

2017-03-31 12:38 UTC, dhavalsharma commented on civihr_default_theme/scss/components/_leave-request-modal.scss
> +.chr_leave-request-modal__input-font-size {
do you mean something like `chr_leave-calendar__legend__label` but its name suggests its for calendar?

2017-03-31 12:41 UTC, dhavalsharma commented on civihr_default_theme/scss/components/_leave-request-modal.scss
> +.chr_leave-request-modal__span-expiry {
It is combination of `control-label` and `label` which caused the text to be mis aligned after addition of `uib-datepicker-popup` for expiry date. 
If i use `form-control` in span it gives a border rectangle but aligns it well. is that ok?

2017-04-03 10:03 UTC, AkA84 approved these changes
@dhavalsharma approved, but squash the PR review commits

2017-04-03 11:27 UTC, merged