PCHR-2002: Add css for absence tab page
compucorp/civihr-employee-portal-theme pull request #155
Opened 2017-04-14 11:44 UTC by dhavalsharma

Added the styles for the absence tab page.

## Screenshot

![image](https://cloud.githubusercontent.com/assets/89973/25042449/c26bd742-2135-11e7-958d-054b59dbd8da.png)

2017-04-17 06:15 UTC, deb1990 commented
1. "Create New" should be in block letters.
2. Record staff sickness and Record staff overtime dropdown not working.
3. Tab switiching now working
4. Tabs dont have hand cursor

2017-04-17 06:15 UTC, deb1990 commented
![civihr_staff_compucorp_co_uk___hr17](https://cloud.githubusercontent.com/assets/5058867/25080655/5fa92152-2363-11e7-9f27-67fc67347d27.png)
Arrow not center alighned

2017-04-17 06:17 UTC, deb1990 commented
![civihr_staff_compucorp_co_uk___hr17](https://cloud.githubusercontent.com/assets/5058867/25080687/8bf44872-2363-11e7-9e14-dd60ea561e3e.png)
As hover style is not mentioned in the mock, lets follow what we have. That is, there should not be any style change on hovered. Please refer My Leave or Manager Leave page.

2017-04-17 06:39 UTC, deb1990 requested changes

2017-04-17 06:39 UTC, deb1990 commented on civihr_default_theme/scss/pages/_admin_absence_tab.scss
> +.chr_leave-absences-admin {
Is this required? Cant find it being used in the code.

2017-04-17 06:39 UTC, deb1990 commented on civihr_default_theme/scss/pages/_admin_absence_tab.scss
> +.chr_absence-tab-page {
`absence-tab-page`

2017-04-17 06:39 UTC, deb1990 commented on civihr_default_theme/scss/pages/_admin_absence_tab.scss
> +    ul {
Not required when you put `<div class="container">` in the html

2017-04-17 06:39 UTC, deb1990 commented on civihr_default_theme/scss/pages/_admin_absence_tab.scss
> +.chr_absence-tab-page--active_bottom {
`chr_absence-tab-page--active_bottom` should not be created. Active class is already present in tabs, see how it is done for My Leave and Manager leave(Blue bottom border). And just override it.

2017-04-17 06:39 UTC, deb1990 commented on civihr_default_theme/scss/pages/_admin_absence_tab.scss
> +  .btn-group {
Do we need to override these settings?

2017-04-17 06:39 UTC, deb1990 commented on civihr_default_theme/scss/pages/_admin_absence_tab.scss
> +.chr_absence-tab-page {
A lot of things are changed for the tabs which seems unnecessary to me as the tabs are same as manager and my leave. Only the active tab color and `button-container` margin seems different to me.

2017-04-17 10:19 UTC, dhavalsharma commented on civihr_default_theme/scss/pages/_admin_absence_tab.scss
> +  .btn-group {
yes to reduce the width and added comment for rest

2017-04-17 10:20 UTC, dhavalsharma commented on civihr_default_theme/scss/pages/_admin_absence_tab.scss
> +    ul {
ul is required to customize certain styles to match design like border bottom etc.,

2017-04-17 10:20 UTC, dhavalsharma commented on civihr_default_theme/scss/pages/_admin_absence_tab.scss
> +.chr_absence-tab-page {
the design is totally different from what is there in my leave or manager leave, see the comments in css

2017-04-17 11:24 UTC, deb1990 requested changes
Please update screenshot, also provide screenshot when the dropdown is open.

2017-04-17 11:24 UTC, deb1990 commented on civihr_default_theme/scss/pages/_admin_absence_tab.scss
> +    .container {
Line break

2017-04-17 11:24 UTC, deb1990 commented on civihr_default_theme/scss/pages/_admin_absence_tab.scss
>            font-size: 14px;
Use SCSS variables, you may need to create new variable for 14px

2017-04-17 11:24 UTC, deb1990 commented on civihr_default_theme/scss/base/_variables.scss
> +$crm-dark:               #000000 !default;
Indentation does not match, also in the design the color is not black its, '4c4c5d'. Please use $gray-darker:

2017-04-17 11:24 UTC, deb1990 commented on civihr_default_theme/scss/pages/_admin_absence_tab.scss
> +      margin-left: 0;
`margin: 0;` would be better as we dont want any margin.

2017-04-17 11:24 UTC, deb1990 commented on civihr_default_theme/scss/pages/_admin_absence_tab.scss
>        background: white;
Use variables, no color should be directly used

2017-04-17 11:24 UTC, deb1990 commented on civihr_default_theme/scss/pages/_admin_absence_tab.scss
> +            border-width: 0px;
I removed it and did not see any difference.

2017-04-17 11:24 UTC, deb1990 commented on civihr_default_theme/scss/pages/_admin_absence_tab.scss
> +              border: 0 !important;
`!imporant` should be used only if necessary. Here I removed and it still works.

2017-04-17 11:24 UTC, deb1990 commented on civihr_default_theme/scss/pages/_admin_absence_tab.scss
>        font-weight: 200;
Use font-weight variables

2017-04-17 13:15 UTC, dhavalsharma commented on civihr_default_theme/scss/pages/_admin_absence_tab.scss
> +      margin-left: 0;
rest of the margins are already 0 , so not re-setting again

2017-04-17 13:53 UTC, dhavalsharma commented on civihr_default_theme/scss/pages/_admin_absence_tab.scss
> +            border-width: 0px;
if i remove this is what i get 
![image](https://cloud.githubusercontent.com/assets/89973/25090854/4dcad300-23a3-11e7-9a60-35185933e3ed.png)

2017-04-18 05:32 UTC, deb1990 requested changes

2017-04-18 05:32 UTC, deb1990 commented on civihr_default_theme/scss/pages/_admin_absence_tab.scss
> +          border-width: 0px;
Dont use unit with 0.

2017-04-18 05:32 UTC, deb1990 commented on civihr_default_theme/scss/pages/_admin_absence_tab.scss
> +            border-width: 0px;
Dont use unit with 0.

2017-08-24 11:47 UTC, closed without merging

2017-08-24 11:49 UTC, davialexandre commented
I'm closing this as it became stale and we probably don't need it anymore. I'll keep the branch for now. If we really don't need it, the branch will be deleted on the next branch cleanup