PCHR-2206: Fix contact selection dropdown styles
compucorp/civihr-employee-portal-theme pull request #160
Opened 2017-05-18 10:58 UTC by dhavalsharma

## Overview
_A brief description of the pull request. Try to keep it non-technical. Please mark your pull request with the appropriate [label(s)](https://github.com/compucorp/civihr-employee-portal-theme/blob/staging/CONTRIBUTING.md#label-types)_

## Before
_The current status. Please provide screenshots or gifs ([LICEcap](http://www.cockos.com/licecap/), [SilentCast](https://github.com/colinkeenan/silentcast)) where appropriate._

## After
_What has been changed. Please provide screenshots or gifs ([LICEcap](http://www.cockos.com/licecap/), [SilentCast](https://github.com/colinkeenan/silentcast)) where appropriate._

## Technical Details
_If the PR introduces noteworthy technical changes, please describe them here. Provide code snippets if necessary_

## Comments
_Anything else you would like the reviewer to note_

---

- [ ] Tests Pass

2017-05-19 07:36 UTC, AkA84 commented
@dhavalsharma you are missing the "Before" section, also please make sure that jon and mike confirm that the dropdown looks as expected

2017-05-19 07:39 UTC, AkA84 requested changes

2017-05-19 07:39 UTC, AkA84 commented on civihr_default_theme/scss/components/_ui-select.scss
> +* Dropdown ul opacity was set to 0
why? is this an issue with the ui-select library?

2017-05-19 07:39 UTC, AkA84 commented on civihr_default_theme/scss/components/_ui-select.scss
> -.civihr-ui-select {
related to the comment i made in the other pr, why are we removing the entire civihr-ui-select theme? If we had it before, it means it was necessary. What happened that we can just discard it completely? You give no details in the PR description

2017-05-22 07:45 UTC, dhavalsharma commented on civihr_default_theme/scss/components/_ui-select.scss
> +* Dropdown ul opacity was set to 0
could be , as this is a pop up dialog

2017-05-22 08:12 UTC, dhavalsharma commented on civihr_default_theme/scss/components/_ui-select.scss
> -.civihr-ui-select {
good questions, tried to to git bisect and changed to earlier version of civicrm, could not locate the cause of regression yet

2017-05-22 10:33 UTC, AkA84 approved these changes

2017-05-22 11:07 UTC, merged