PCHR-2144: Temporary _temp_custom.scss style for document modal in SSP
compucorp/civihr-employee-portal-theme pull request #162
Opened 2017-05-26 07:29 UTC by bmnepali

## Overview
_A brief description of the pull request. Try to keep it non-technical. Please mark your pull request with the appropriate [label(s)](https://github.com/compucorp/civihr-employee-portal-theme/blob/staging/CONTRIBUTING.md#label-types)_

## Before
_The current status. Please provide screenshots or gifs ([LICEcap](http://www.cockos.com/licecap/), [SilentCast](https://github.com/colinkeenan/silentcast)) where appropriate._

## After
_What has been changed. Please provide screenshots or gifs ([LICEcap](http://www.cockos.com/licecap/), [SilentCast](https://github.com/colinkeenan/silentcast)) where appropriate._

## Technical Details
_If the PR introduces noteworthy technical changes, please describe them here. Provide code snippets if necessary_

## Comments
_Anything else you would like the reviewer to note_

---

- [ ] Tests Pass

2017-05-26 10:15 UTC, AkA84 requested changes

2017-05-26 10:15 UTC, AkA84 commented on civihr_default_theme/scss/civihr_default_theme.style.scss
> +@import "base/_temp_custom";
put this at the end of the file in a "Temporary" section

2017-05-26 10:15 UTC, AkA84 commented on civihr_default_theme/scss/civihr_default_theme.style.scss
> +@import "base/_temp_custom";
also can you give it a more meaningful name? Like `_task-assignments-modal-temp.scss`

2017-05-26 10:15 UTC, AkA84 commented on civihr_default_theme/scss/civihr_default_theme.style.scss
> +@import "base/_temp_custom";
also, when you `@import` a partial, you don't need to specify the `_` (see other imports in the same file)

2017-05-26 10:27 UTC, bmnepali commented on civihr_default_theme/scss/civihr_default_theme.style.scss
> +@import "base/_temp_custom";
right! will fix it

2017-05-26 10:27 UTC, bmnepali commented on civihr_default_theme/scss/civihr_default_theme.style.scss
> +@import "base/_temp_custom";
will do

2017-05-29 10:40 UTC, dhavalsharma requested changes

2017-05-29 10:40 UTC, dhavalsharma commented on civihr_default_theme/scss/base/_task-assignments-modal-temp.scss
> +// This is the temporary styles to male the new Document modal look similar in SSP
is male make?

2017-05-29 10:41 UTC, dhavalsharma commented
can you also specify the source of this style file for reference here ?

2017-05-29 10:42 UTC, bmnepali commented on civihr_default_theme/scss/base/_task-assignments-modal-temp.scss
> +// This is the temporary styles to male the new Document modal look similar in SSP
Exactly! will fix it

2017-05-29 10:47 UTC, bmnepali commented
@dhavalsharma Most of the styles re custom. Some of the styles taken from 
1. uk.co.compucorp.civicrm.tasksassignments/scss/civihr/partials/_datepicker.scss

2017-05-29 10:51 UTC, dhavalsharma approved these changes

2017-06-01 08:11 UTC, AkA84 approved these changes

2017-06-05 08:56 UTC, AkA84 approved these changes

2017-06-05 11:45 UTC, AkA84 approved these changes

2017-06-06 15:50 UTC, AkA84 approved these changes

2017-06-07 14:46 UTC, merged