PCHR-2317: Namespace temporary styles for doocument modal in ssp
compucorp/civihr-employee-portal-theme pull request #170
Opened 2017-06-14 10:58 UTC by bmnepali

## Overview
This PR is for the hot fix to add name space to temporary styles for the document modal in ssp for staff and manager document sections.

## Before
Before name-spacing temporary styles (issue)
<img width="491" alt="screen shot 2017-06-14 at 12 52 49 pm" src="https://user-images.githubusercontent.com/6307362/27120315-c92e1386-5102-11e7-89cc-192f0fe99307.png">

## After
After name-spacing the temporary styles (issue fixed)
<img width="487" alt="screen shot 2017-06-14 at 12 48 23 pm" src="https://user-images.githubusercontent.com/6307362/27120314-c86d1ce4-5102-11e7-897e-cb7a9e3c0904.png">

## Technical Details
1. Name-spacing the temporary styles for document modal in ssp in file `civihr_employee_portal_theme/civihr_default_theme/scss/base/_task-assignments-modal-temp.scss` 
```css
[data-ta-documents],
[data-ta-documents-manager] {
   // All temporary styles for documents modal
}
```

2017-06-14 12:19 UTC, AkA84 approved these changes

2017-06-21 04:23 UTC, deb1990 commented on civihr_default_theme/scss/base/_task-assignments-modal-temp.scss
> +      max-width: 500px;
Add details about both these changes, why they need to be specified and what is the affect on UI with screenshot before and After.

2017-06-21 04:23 UTC, deb1990 commented
@bmnepali This PR contains 2 commits which are not part of this PR, please remove them.

2017-06-21 04:24 UTC, deb1990 requested changes

2017-06-21 04:24 UTC, deb1990 commented on civihr_default_theme/scss/partials/_block.scss
> +  border-radius: 50%;
This change is not part of this PR it seems.

2017-06-21 04:51 UTC, bmnepali commented on civihr_default_theme/scss/partials/_block.scss
> +  border-radius: 50%;
yes! it is not! removed those two commits.

2017-06-21 05:02 UTC, bmnepali commented on civihr_default_theme/scss/base/_task-assignments-modal-temp.scss
> +      max-width: 500px;
Updated Description with the changes and explanations.

2017-06-21 05:03 UTC, bmnepali commented
@deb1990 Thanks, I have removed those two commits and updated the PR description for additional changes.

2017-06-21 05:50 UTC, deb1990 commented on civihr_default_theme/scss/base/_task-assignments-modal-temp.scss
> +      max-width: 500px;
This can be achived by using thee small modal of bootstrap,
http://getbootstrap.com/javascript/#modals-sizes

2017-06-21 06:09 UTC, bmnepali commented on civihr_default_theme/scss/base/_task-assignments-modal-temp.scss
> +      max-width: 500px;
Actually, the modal is being reused form T&A and works fine  in T&A. But the styles are not present in SSP as we are using different theme than T&A. So the width needs to be displayed s above, which is temporary for now.

2017-06-21 06:19 UTC, deb1990 approved these changes

2017-06-21 08:20 UTC, merged