PCHR-2033: Move styles to L&A
compucorp/civihr-employee-portal-theme pull request #182
Opened 2017-07-04 11:11 UTC by deb1990

`_manager_calendar.scss` is moved to Leave and Absence extension(https://github.com/civicrm/civihr/pull/1981).

2017-07-04 11:50 UTC, igorpavlov-zz requested changes

2017-07-04 11:50 UTC, igorpavlov commented on civihr_default_theme/scss/civihr_default_theme.style.scss
> +@import "SCSSROOT/uk.co.compucorp.civicrm.hrleaveandabsences/scss/components/manager_calendar";
I am not sure this should be called manager calendar. We might consider renaming files as it becomes a shared component.

2017-07-04 16:34 UTC, deb1990 commented on civihr_default_theme/scss/civihr_default_theme.style.scss
> +@import "SCSSROOT/uk.co.compucorp.civicrm.hrleaveandabsences/scss/components/manager_calendar";
I think `manager_calendar` is still fine because still it shows the calendar for the managees. Admin is getting all contacts because he manages all.

2017-07-05 09:05 UTC, igorpavlov-zz approved these changes

2017-07-05 09:06 UTC, merged