PCHR-2358: Add user guide link + modified footer in ssp pages
compucorp/civihr-employee-portal-theme pull request #187
Opened 2017-07-12 14:11 UTC by bmnepali

## Overview
- A new sub-menu in account menu in SSP. 
- Modify footer for SSP pages

## After
Displays sub menu in account menu in SSP.
![screen shot 2017-07-12 at 7 51 23 pm](https://user-images.githubusercontent.com/6307362/28121675-9437b8ae-673b-11e7-8d69-ad28156a55d0.png)

## Technical Details:
1. Modify "civihr_default_theme/templates/page/page.tpl.php" for sub menu
```html
<ul class="chr_header__sub-menu">
   ...
   <li><?php print $user_guide_link; ?></li>
</ul>
```
2. Modify "" file for tooter.
```html
<div class="text-center">
    Powered by CiviHR <?php print get_civihr_version(); ?>.
    CiviHR is openly available under the <a href="http://www.gnu.org/licenses/agpl-3.0.html">GNU 
    AGPL License</a> and can be downloaded from
    <a target="_blank" href="https://civihr.org">Project website</a>&nbsp;.
    <div class="footer-logo">
    <i class="icon-logo-full"></i>
</div>
```

## Comments
_ Removed not required markups for the footer.

2017-07-12 14:52 UTC, mickadoo commented
Typo in description "file for tooter"

2017-07-12 14:55 UTC, mickadoo approved these changes
Looks good :sunflower:

2017-07-12 15:06 UTC, bmnepali commented
Updated PR description!

2017-07-12 15:13 UTC, mickadoo reviewed
Just a question on something I missed first time around

2017-07-12 15:13 UTC, mickadoo commented on civihr_default_theme/templates/page/page.tpl.php
> +        CiviHR is openly available under the <a href="http://www.gnu.org/licenses/agpl-3.0.html">GNU AGPL License</a> and can be downloaded from
Maybe you should check with Mike, but "downloaded from Project Website" seems a bit strange without a "the"

2017-07-12 15:44 UTC, bmnepali commented on civihr_default_theme/templates/page/page.tpl.php
> +        CiviHR is openly available under the <a href="http://www.gnu.org/licenses/agpl-3.0.html">GNU AGPL License</a> and can be downloaded from
Fixed as discussed with Mike.

2017-07-12 16:33 UTC, mickadoo requested changes
Typo after fixing link text

2017-07-12 16:33 UTC, mickadoo commented on civihr_default_theme/templates/page/page.tpl.php
> +        CiviHR is openly available under the <a href="http://www.gnu.org/licenses/agpl-3.0.html">GNU AGPL License</a> and can be downloaded from the onkeyup=""<a target="_blank" href="https://civihr.
> downloaded from the onkeyup

2017-07-12 16:39 UTC, bmnepali commented on civihr_default_theme/templates/page/page.tpl.php
> +        CiviHR is openly available under the <a href="http://www.gnu.org/licenses/agpl-3.0.html">GNU AGPL License</a> and can be downloaded from the onkeyup=""<a target="_blank" href="https://civihr.
Fixed!

2017-07-12 16:53 UTC, mickadoo approved these changes

2017-07-27 11:41 UTC, coldrunKacper approved these changes

2017-08-01 08:22 UTC, deb1990 approved these changes

2017-08-02 10:52 UTC, merged