PCHR-2490: Document modal v2 update
compucorp/civihr-employee-portal-theme pull request #206
Opened 2017-08-23 08:23 UTC by bmnepali

## Overview
This PR adds styles for indicating required files in document modal and also fixed the width issue in datepicker.

## Before
- No validation styles for files field:
<img width="519" alt="screen shot 2017-08-23 at 2 03 29 pm" src="https://user-images.githubusercontent.com/6307362/29605863-21fc484e-880c-11e7-9350-54d072132704.png">

- Date picker width was broken
<img width="647" alt="screen shot 2017-08-23 at 2 03 03 pm" src="https://user-images.githubusercontent.com/6307362/29605850-160a1066-880c-11e7-87d1-5550480d4640.png">

## After
- Added style for displaying required filed field for staff user
<img width="513" alt="screen shot 2017-08-23 at 2 02 07 pm" src="https://user-images.githubusercontent.com/6307362/29605855-1c28ab10-880c-11e7-8413-d58ffae7e519.png">

- Fixed date picker width issue
<img width="523" alt="screen shot 2017-08-23 at 2 02 17 pm" src="https://user-images.githubusercontent.com/6307362/29605841-11a6a67e-880c-11e7-94dd-fa2a367ae6c0.png">

## Technical Details
1. Added a style for indicating required field:
```css
.no-file {
   color: red;
   border-color: #e6230f !important;
}
```
2. Removed width form the date picker dropdown to use default width.
```css
[uib-datepicker-popup-wrap] > .dropdown-menu {
   padding: 10px;
- width: 300px;
} 
```

2017-08-23 08:51 UTC, deb1990 requested changes

2017-08-23 08:51 UTC, deb1990 commented on civihr_default_theme/scss/base/_task-assignments-modal-temp.scss
> +      color: red;
We should use existing color variables here.
Example: bootstrap danger color for red

2017-08-23 09:31 UTC, deb1990 approved these changes

2017-09-08 12:25 UTC, bmnepali commented
Fixed merge conflicts by rebase!

2017-09-18 12:55 UTC, bmnepali commented
Fix merge conflicts by rebase.

2017-09-18 12:56 UTC, merged