PCHR-2573: Sync L&A Styling
compucorp/civihr-employee-portal-theme pull request #223
Opened 2017-09-12 15:32 UTC by igorpavlov

## Overview

This PR simply syncs styling from https://github.com/civicrm/civihr/pull/2133.

2017-09-12 16:52 UTC, reneolivo requested changes
Please fix conflicts

2017-09-13 11:44 UTC, igorpavlov commented
@reneolivo conflicts fixed

2017-09-13 11:48 UTC, reneolivo approved these changes

2017-09-13 12:11 UTC, igorpavlov commented
This PR is not needed anymore since the CSS files were built and synced during sync with 1.6

2017-09-13 12:40 UTC, merged