Pchr 2707 breadcrumb styling
compucorp/civihr-employee-portal-theme pull request #236
Opened 2017-10-03 09:07 UTC by deb1990

## Overview
_A brief description of the pull request. Try to keep it non-technical. Please mark your pull request with the appropriate [label(s)](https://github.com/compucorp/civihr-employee-portal-theme/blob/staging/CONTRIBUTING.md#label-types)_

## Before
_The current status. Please provide screenshots or gifs ([LICEcap](http://www.cockos.com/licecap/), [SilentCast](https://github.com/colinkeenan/silentcast)) where appropriate._

## After
_What has been changed. Please provide screenshots or gifs ([LICEcap](http://www.cockos.com/licecap/), [SilentCast](https://github.com/colinkeenan/silentcast)) where appropriate._

## Technical Details
_If the PR introduces noteworthy technical changes, please describe them here. Provide code snippets if necessary_

## Comments
_Anything else you would like the reviewer to note_

---

- [ ] Tests Pass

2017-10-03 12:17 UTC, reneolivo requested changes
please try to reuse code from this wizard component as much as possible:

* https://github.com/civicrm/org.civicrm.shoreditch/blob/926982a914cf6482562626219a71a434e34f4d79/scss/civicrm/common/_wizard.scss

2017-10-04 08:11 UTC, deb1990 commented
> please try to reuse code from this wizard component as much as possible:

@reneolivo I found that, there are 2 css available available for the wizard, the other one is https://github.com/compucorp/org.civicrm.shoreditch/blob/bd98a32ca66c44d57b6053d2f50499a58663e6e0/scss/bootstrap/components/_wizard.scss#L12-L12. And the same is used in `/civicrm/admin/leaveandabsences/import`, so I used that one here.

2017-10-04 10:53 UTC, reneolivo approved these changes

2017-10-04 14:01 UTC, mickadoo requested changes
@deb1990 just a reminder that the template should not be always overridden and you should copy your changes from the template file in this into [this file](https://github.com/compucorp/civihr-employee-portal-theme/blob/PCHR-2339-onboarding-wizard/civihr_default_theme/templates/contrib/webform-onboarding-progressbar.tpl.php)

2017-10-04 14:01 UTC, mickadoo commented on civihr_default_theme/templates/node/webform-progressbar.tpl.php
> +/**
Wouldn't this mean that all webform progress bars would use the overridden template?

2017-10-11 11:58 UTC, merged