PCHR-4427: Fix vulnerability issues
compucorp/civihr-employee-portal-theme pull request #390
Opened 2018-11-27 16:31 UTC by AkA84

### IN PROGRESS

## Overview
_A brief description of the pull request. Try to keep it non-technical. Please mark your pull request with the appropriate [label(s)](https://github.com/compucorp/civihr-employee-portal-theme/blob/staging/CONTRIBUTING.md#label-types)_

## Before
_The current status. Please provide screenshots or gifs ([LICEcap](http://www.cockos.com/licecap/), [SilentCast](https://github.com/colinkeenan/silentcast)) where appropriate._

## After
_What has been changed. Please provide screenshots or gifs ([LICEcap](http://www.cockos.com/licecap/), [SilentCast](https://github.com/colinkeenan/silentcast)) where appropriate._

## Technical Details
_If the PR introduces noteworthy technical changes, please describe them here. Provide code snippets if necessary_

## Comments
_Anything else you would like the reviewer to note_

---

- [ ] Tests Pass

2018-11-27 16:54 UTC, igorpavlov commented
Could you include 2 screenshots of versions of a sample image (before/after)?

2018-11-27 16:58 UTC, AkA84 commented
@igorpavlov done

2018-11-27 17:02 UTC, igorpavlov-zz requested changes

2018-11-27 17:02 UTC, igorpavlov commented on civihr_default_theme/assets/images/spinner.svg
> +<svg xmlns="http://www.w3.org/2000/svg" data-name="Layer 1" viewBox="0 0 80 80"><path fill="#0071BD" d="M40 72C22.4 72 8 57.6 8 40S22.4 8 40 8s32 14.4 32 32c0 1.1-.9 2-2 2s-2-.9-2-2c0-15.4-12.6-28-28
Probably need an end line

2018-11-27 17:03 UTC, igorpavlov commented on civihr_default_theme/assets/images/spinner.svg
> +<svg xmlns="http://www.w3.org/2000/svg" data-name="Layer 1" viewBox="0 0 80 80"><path fill="#0071BD" d="M40 72C22.4 72 8 57.6 8 40S22.4 8 40 8s32 14.4 32 32c0 1.1-.9 2-2 2s-2-.9-2-2c0-15.4-12.6-28-28
![image](https://user-images.githubusercontent.com/3973243/49098230-55827880-f266-11e8-8878-9401b8332c12.png)

2018-11-27 17:14 UTC, igorpavlov-zz approved these changes

2018-11-27 17:15 UTC, igorpavlov commented
@AkA84 it seems that every time we run `gulp images` it will remove the end line from the svg file (maybe from other files as well). This should be checked so it does not break things.

2018-11-28 07:37 UTC, AkA84 commented
@igorpavlov that's correct, so there's no point trying to add the new line manually. I've forced pushed the svg file as created by the gulp task

2018-11-28 10:46 UTC, merged